/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.feevale.tirimania.view;

import com.feevale.tirimania.controller.GerarNotaFiscal;
import com.feevale.tirimania.controller.SalvarPedido;
import com.feevale.tirimania.model.Item;
import com.feevale.tirimania.model.Pedido;
import com.feevale.tirimania.model.Sabor;
import com.feevale.tirimania.model.gerador.GeradorDeTiposDePedidos;

import javax.swing.*;

import static com.feevale.tirimania.Main.trocarTela;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author vitoria
 */
public class NewOrder extends javax.swing.JPanel {

    private Pedido pedido = new Pedido();
    
    /**
     * Creates new form Home
     */
    public NewOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSabor = new javax.swing.JLabel();
        buttonAddPedido = new javax.swing.JButton();
        txtItensPedidos = new javax.swing.JLabel();
        listaPedidosAdd = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        buttonExcluirPedido = new javax.swing.JButton();
        txtValorPedido = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        buttonConcluir = new javax.swing.JButton();
        buttonNotaFiscal = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("Cancelar pedido");
        jButton3.setActionCommand("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonExcluirPedido.addActionListener(this::removerItem);

        jPasswordField1.setText("jPasswordField1");

        Titulo.setFont(new java.awt.Font("OCR A Extended", 1, 50)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 0, 51));
        Titulo.setText("DOG MANIA");

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 16)); // NOI18N
        jLabel1.setText("Novo Pedido");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel2.setText("Lanches/Bebidas:");

        txtSabor.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtSabor.setText("Sabor:");

        buttonAddPedido.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        buttonAddPedido.setForeground(new java.awt.Color(51, 153, 0));
        buttonAddPedido.setText("Adicionar Item Ao Pedido");
        buttonAddPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPedidoActionPerformed(evt);
            }
        });

        txtItensPedidos.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        txtItensPedidos.setText("Itens do pedido:");

        listaPedidosAdd.setViewportView(jList2);

        buttonExcluirPedido.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        buttonExcluirPedido.setForeground(new java.awt.Color(255, 0, 0));
        buttonExcluirPedido.setText("Excluir Item do Pedido ");

        txtValorPedido.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtValorPedido.setText("Total do pedido:");

        buttonCancelar.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(255, 0, 0));
        buttonCancelar.setText("Cancelar pedido");
        buttonCancelar.setActionCommand("");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonConcluir.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        buttonConcluir.setForeground(new java.awt.Color(0, 153, 0));
        buttonConcluir.setText("Concluir pedido");
        buttonConcluir.setActionCommand("");
        buttonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarActionPerformed(evt);
            }
        });

        buttonNotaFiscal.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        buttonNotaFiscal.setForeground(new java.awt.Color(0, 0, 255));
        buttonNotaFiscal.setText("Gerar Nota Fiscal");
        buttonNotaFiscal.setActionCommand("");
        buttonNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNotaFiscalActionPerformed(evt);
            }
        });

        buttonVoltar.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        buttonVoltar.setForeground(new java.awt.Color(0, 0, 255));
        buttonVoltar.setText("Voltar");
        buttonVoltar.setActionCommand("");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(GeradorDeTiposDePedidos.getAlimentos()));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarItens(evt);
            }
        });
        Item selecionado = (Item) jComboBox1.getSelectedItem();
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(selecionado.getSabores()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtItensPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107)
                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(listaPedidosAdd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAddPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonExcluirPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonConcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buttonNotaFiscal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAddPedido)
                .addGap(45, 45, 45)
                .addComponent(txtItensPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaPedidosAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluirPedido)
                .addGap(34, 34, 34)
                .addComponent(txtValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonConcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVoltar)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valorPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPedidoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int retorno = showConfirmDialog(null, "Certeza que quer cancelar?");
        if (retorno == 0)
            trocarTela(new Home());
    }

    private void buttonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        int retorno = showConfirmDialog(null, "Certeza que quer concluir?");
        if (retorno == 0){
            boolean salvo = SalvarPedido.salvarPedido(pedido);
            if(!salvo)
                showMessageDialog(null, "Erro ao finalizar pedido!");
            else {
                int gerarNotaFiscal = showConfirmDialog(null, "Gerar Nota Fiscal?");
                if(gerarNotaFiscal == 0) {
                    GerarNotaFiscal.gerarNotaFiscal(pedido);
//                    trocarTela(new Home());
                }
            }
        }

    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNotaFiscalActionPerformed
        // TODO add your handling code here:
        GerarNotaFiscal.gerarNotaFiscal(pedido);
    }//GEN-LAST:event_buttonNotaFiscalActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // TODO add your handling code here:
        trocarTela(new Home());
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonAddPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPedidoActionPerformed
        Item selecionado = (Item) jComboBox1.getSelectedItem();
        Sabor saborSelecionado = (Sabor) jComboBox2.getSelectedItem();
        selecionado.selecionarSabor(saborSelecionado);
        pedido.adicionarItem(selecionado);

        atualizarListaDePedidos();
    }//GEN-LAST:event_buttonAddPedidoActionPerformed

    private void atualizarListaDePedidos() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        pedido.getItens().forEach(element -> listModel.addElement(element.toString() + " " + element.getSaborSelecionado() +  " " + " R$ " + element.getPreco()));
        jList2.setModel(listModel);

        txtValorPedido.setText("Valor: R$ " + pedido.getValorTotal());
    }

    private void atualizarItens(java.awt.event.ActionEvent evt) {
        Item selecionado = (Item) jComboBox1.getSelectedItem();
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(selecionado.getSabores()));
    }

    private void removerItem(java.awt.event.ActionEvent evt) {
        int index = jList2.getSelectedIndex();
        pedido.removerItem(index);
        atualizarListaDePedidos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton buttonAddPedido;
    private javax.swing.JButton buttonConcluir;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonExcluirPedido;
    private javax.swing.JButton buttonNotaFiscal;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Item> jComboBox1;
    private javax.swing.JComboBox<Sabor> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane listaPedidosAdd;
    private javax.swing.JLabel txtItensPedidos;
    private javax.swing.JLabel txtSabor;
    private javax.swing.JLabel txtValorPedido;
}
